<a href="https://colab.research.google.com/github/majorquev/DBDC_202209_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_02_listas_y_dataframes_desarrollo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto). 
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [5]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = 3,
           letra = c("A","Z","X"),
           mat = diag(1:3),
           sub_lista = list(otro_num = 8:11, fechas = seq(as.Date("2022-09-26"),as.Date("2022-12-26"), by =1) )
           )

In [6]:
l1

$num
[1] 3

$letra
[1] "A" "Z" "X"

$mat
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$sub_lista
$sub_lista$otro_num
[1]  8  9 10 11

$sub_lista$fechas
 [1] "2022-09-26" "2022-09-27" "2022-09-28" "2022-09-29" "2022-09-30"
 [6] "2022-10-01" "2022-10-02" "2022-10-03" "2022-10-04" "2022-10-05"
[11] "2022-10-06" "2022-10-07" "2022-10-08" "2022-10-09" "2022-10-10"
[16] "2022-10-11" "2022-10-12" "2022-10-13" "2022-10-14" "2022-10-15"
[21] "2022-10-16" "2022-10-17" "2022-10-18" "2022-10-19" "2022-10-20"
[26] "2022-10-21" "2022-10-22" "2022-10-23" "2022-10-24" "2022-10-25"
[31] "2022-10-26" "2022-10-27" "2022-10-28" "2022-10-29" "2022-10-30"
[36] "2022-10-31" "2022-11-01" "2022-11-02" "2022-11-03" "2022-11-04"
[41] "2022-11-05" "2022-11-06" "2022-11-07" "2022-11-08" "2022-11-09"
[46] "2022-11-10" "2022-11-11" "2022-11-12" "2022-11-13" "2022-11-14"
[51] "2022-11-15" "2022-11-16" "2022-11-17" "2022-11-18" "2022-11-19"
[56] "2022-11-20" "2022-11-21" "2022-11-22" "2022-11-23" "2022-11-24"
[61] "2022-11-25" "2022-11-26" "2022-11-27" "2022-11-28" "2022-11-29"
[66] "2022-11-30" "2022-12-01" "2022-12-02" "2022-12-03" "2022-12-04"
[71] "2022-12-05" "2022-12-06" "2022-12-07" "2022-12-08" "2022-12-09"
[76] "2022-12-10" "2022-12-11" "2022-12-12" "2022-12-13" "2022-12-14"
[81] "2022-12-15" "2022-12-16" "2022-12-17" "2022-12-18" "2022-12-19"
[86] "2022-12-20" "2022-12-21" "2022-12-22" "2022-12-23" "2022-12-24"
[91] "2022-12-25" "2022-12-26"

In [7]:
# estructura
str(l1)

List of 4
 $ num      : num 3
 $ letra    : chr [1:3] "A" "Z" "X"
 $ mat      : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista:List of 2
  ..$ otro_num: int [1:4] 8 9 10 11
  ..$ fechas  : Date[1:92], format: "2022-09-26" "2022-09-27" ...


In [9]:
length(l1)
names(l1)

[1] 4

[1] "num"       "letra"     "mat"       "sub_lista"

In [11]:
# Podemos guardar los objetos en slots con nombres como en l1, o bien sin nomrbes

l2 <- list(2, c(T,F,T))
l2

[[1]]
[1] 2

[[2]]
[1]  TRUE FALSE  TRUE

In [13]:
names(l2) <- c("nuevo_num", "otro_vect")

In [14]:
str(l2)

List of 2
 $ nuevo_num: num 2
 $ otro_vect: logi [1:3] TRUE FALSE TRUE


In [16]:
# Podemos combinar listas
l3 <- c(l1,l2)
str(l3)

List of 6
 $ num      : num 3
 $ letra    : chr [1:3] "A" "Z" "X"
 $ mat      : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista:List of 2
  ..$ otro_num: int [1:4] 8 9 10 11
  ..$ fechas  : Date[1:92], format: "2022-09-26" "2022-09-27" ...
 $ nuevo_num: num 2
 $ otro_vect: logi [1:3] TRUE FALSE TRUE


In [21]:
# Acceso mediante posición
l3[2]

$letra
[1] "A" "Z" "X"

In [19]:
class(l3[2])

[1] "list"

In [18]:
class(c("f","g"))

[1] "character"

In [23]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]

l3[[2]]
class(l3[[2]])

[1] "A" "Z" "X"

[1] "character"

In [27]:
str(l3)

List of 6
 $ num      : num 3
 $ letra    : chr [1:3] "A" "Z" "X"
 $ mat      : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista:List of 2
  ..$ otro_num: int [1:4] 8 9 10 11
  ..$ fechas  : Date[1:92], format: "2022-09-26" "2022-09-27" ...
 $ nuevo_num: num 2
 $ otro_vect: logi [1:3] TRUE FALSE TRUE


In [26]:
# del vector que está en la pos 2 de la lista l3, quiero el tercer elemento ("X")
l3[[2]][3]

vector_de_l3 <- l3[[2]]

vector_de_l3[3]


[1] "X"

[1] "X"

In [31]:
# de la lista l3[[4]], quiero el vector (no la lista con el vector) que está en el slot llamado "otro_num" (primer elemento)
l3[[4]][[1]]

[1]  8  9 10 11

In [32]:
# Y si de lo anterior queremos el tercer elmento
l3[[4]][[1]][3]

[1] 10

In [35]:
# Acceso mediante nombre
l3[["sub_lista"]][["otro_num"]][3]


[1] 10

In [39]:
# acceso vía "$" para acceder directamente al elemento sin pasar por la lista que lo contiene

l3$otro_vect

# es equivalente a l3[["otro_vect"]]





[1]  TRUE FALSE  TRUE

[1]  TRUE FALSE  TRUE

In [41]:
l3$sub_lista$otro_num[3]

[1] 10

In [45]:
# para saber el largo de la lista/vector
length(l3)
# Para obtener los nombres de la lista
names(l3)
# si quisiéramos renombrar los slots:
names(l3)[3] <- "matriz"

[1] 6

[1] "num"       "letra"     "mat"       "sub_lista" "nuevo_num" "otro_vect"

In [46]:
str(l3)

List of 6
 $ num      : num 3
 $ letra    : chr [1:3] "A" "Z" "X"
 $ matriz   : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista:List of 2
  ..$ otro_num: int [1:4] 8 9 10 11
  ..$ fechas  : Date[1:92], format: "2022-09-26" "2022-09-27" ...
 $ nuevo_num: num 2
 $ otro_vect: logi [1:3] TRUE FALSE TRUE


In [48]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l3[["nombres"]] <- c("miguel", "Ale")

In [49]:
l3

$num
[1] 3

$letra
[1] "A" "Z" "X"

$matriz
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$sub_lista
$sub_lista$otro_num
[1]  8  9 10 11

$sub_lista$fechas
 [1] "2022-09-26" "2022-09-27" "2022-09-28" "2022-09-29" "2022-09-30"
 [6] "2022-10-01" "2022-10-02" "2022-10-03" "2022-10-04" "2022-10-05"
[11] "2022-10-06" "2022-10-07" "2022-10-08" "2022-10-09" "2022-10-10"
[16] "2022-10-11" "2022-10-12" "2022-10-13" "2022-10-14" "2022-10-15"
[21] "2022-10-16" "2022-10-17" "2022-10-18" "2022-10-19" "2022-10-20"
[26] "2022-10-21" "2022-10-22" "2022-10-23" "2022-10-24" "2022-10-25"
[31] "2022-10-26" "2022-10-27" "2022-10-28" "2022-10-29" "2022-10-30"
[36] "2022-10-31" "2022-11-01" "2022-11-02" "2022-11-03" "2022-11-04"
[41] "2022-11-05" "2022-11-06" "2022-11-07" "2022-11-08" "2022-11-09"
[46] "2022-11-10" "2022-11-11" "2022-11-12" "2022-11-13" "2022-11-14"
[51] "2022-11-15" "2022-11-16" "2022-11-17" "2022-11-18" "2022-11-19"
[56] "2022-11-20" "2022-11-21" "2022-11-22" "2022-11-23" "2022-11-24"
[61] "2022-11-25" "2022-11-26" "2022-11-27" "2022-11-28" "2022-11-29"
[66] "2022-11-30" "2022-12-01" "2022-12-02" "2022-12-03" "2022-12-04"
[71] "2022-12-05" "2022-12-06" "2022-12-07" "2022-12-08" "2022-12-09"
[76] "2022-12-10" "2022-12-11" "2022-12-12" "2022-12-13" "2022-12-14"
[81] "2022-12-15" "2022-12-16" "2022-12-17" "2022-12-18" "2022-12-19"
[86] "2022-12-20" "2022-12-21" "2022-12-22" "2022-12-23" "2022-12-24"
[91] "2022-12-25" "2022-12-26"


$nuevo_num
[1] 2

$otro_vect
[1]  TRUE FALSE  TRUE

$nombres
[1] "miguel" "Ale"

In [51]:
l3$otros_nombres <- c("Jorge", "Rodrigo","Àngel")

In [54]:
c(l3[1:3], list(otra_cosa = 1000), l3[4:8])

$num
[1] 3

$letra
[1] "A" "Z" "X"

$matriz
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3

$otra_cosa
[1] 1000

$sub_lista
$sub_lista$otro_num
[1]  8  9 10 11

$sub_lista$fechas
 [1] "2022-09-26" "2022-09-27" "2022-09-28" "2022-09-29" "2022-09-30"
 [6] "2022-10-01" "2022-10-02" "2022-10-03" "2022-10-04" "2022-10-05"
[11] "2022-10-06" "2022-10-07" "2022-10-08" "2022-10-09" "2022-10-10"
[16] "2022-10-11" "2022-10-12" "2022-10-13" "2022-10-14" "2022-10-15"
[21] "2022-10-16" "2022-10-17" "2022-10-18" "2022-10-19" "2022-10-20"
[26] "2022-10-21" "2022-10-22" "2022-10-23" "2022-10-24" "2022-10-25"
[31] "2022-10-26" "2022-10-27" "2022-10-28" "2022-10-29" "2022-10-30"
[36] "2022-10-31" "2022-11-01" "2022-11-02" "2022-11-03" "2022-11-04"
[41] "2022-11-05" "2022-11-06" "2022-11-07" "2022-11-08" "2022-11-09"
[46] "2022-11-10" "2022-11-11" "2022-11-12" "2022-11-13" "2022-11-14"
[51] "2022-11-15" "2022-11-16" "2022-11-17" "2022-11-18" "2022-11-19"
[56] "2022-11-20" "2022-11-21" "2022-11-22" "2022-11-23" "2022-11-24"
[61] "2022-11-25" "2022-11-26" "2022-11-27" "2022-11-28" "2022-11-29"
[66] "2022-11-30" "2022-12-01" "2022-12-02" "2022-12-03" "2022-12-04"
[71] "2022-12-05" "2022-12-06" "2022-12-07" "2022-12-08" "2022-12-09"
[76] "2022-12-10" "2022-12-11" "2022-12-12" "2022-12-13" "2022-12-14"
[81] "2022-12-15" "2022-12-16" "2022-12-17" "2022-12-18" "2022-12-19"
[86] "2022-12-20" "2022-12-21" "2022-12-22" "2022-12-23" "2022-12-24"
[91] "2022-12-25" "2022-12-26"


$nuevo_num
[1] 2

$otro_vect
[1]  TRUE FALSE  TRUE

$nombres
[1] "miguel" "Ale"   

$otros_nombres
[1] "Jorge"   "Rodrigo" "Àngel"

In [52]:
str(l3)

List of 8
 $ num          : num 3
 $ letra        : chr [1:3] "A" "Z" "X"
 $ matriz       : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista    :List of 2
  ..$ otro_num: int [1:4] 8 9 10 11
  ..$ fechas  : Date[1:92], format: "2022-09-26" "2022-09-27" ...
 $ nuevo_num    : num 2
 $ otro_vect    : logi [1:3] TRUE FALSE TRUE
 $ nombres      : chr [1:2] "miguel" "Ale"
 $ otros_nombres: chr [1:3] "Jorge" "Rodrigo" "Àngel"


In [55]:
# podemos modificar elementos dentro de un slot
# Cmbiar la Z del vector "letra", por una "W"

l3$letra[2] <- "W"
str(l3)



List of 8
 $ num          : num 3
 $ letra        : chr [1:3] "A" "W" "X"
 $ matriz       : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista    :List of 2
  ..$ otro_num: int [1:4] 8 9 10 11
  ..$ fechas  : Date[1:92], format: "2022-09-26" "2022-09-27" ...
 $ nuevo_num    : num 2
 $ otro_vect    : logi [1:3] TRUE FALSE TRUE
 $ nombres      : chr [1:2] "miguel" "Ale"
 $ otros_nombres: chr [1:3] "Jorge" "Rodrigo" "Àngel"


In [56]:
l3$sub_lista$otros_nombres

NULL

In [57]:
l3$sub_lista$otros_nombres <- c("Jorge", "Rodrigo","Àngel")

In [58]:
str(l3)

List of 8
 $ num          : num 3
 $ letra        : chr [1:3] "A" "W" "X"
 $ matriz       : int [1:3, 1:3] 1 0 0 0 2 0 0 0 3
 $ sub_lista    :List of 3
  ..$ otro_num     : int [1:4] 8 9 10 11
  ..$ fechas       : Date[1:92], format: "2022-09-26" "2022-09-27" ...
  ..$ otros_nombres: chr [1:3] "Jorge" "Rodrigo" "Àngel"
 $ nuevo_num    : num 2
 $ otro_vect    : logi [1:3] TRUE FALSE TRUE
 $ nombres      : chr [1:2] "miguel" "Ale"
 $ otros_nombres: chr [1:3] "Jorge" "Rodrigo" "Àngel"


### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí. 

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.
 
 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [82]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)

df <- data.frame(nombre = c("Miguel", "Ale", "Israel"),
                 edad = c(33,29,28),
                 id = 1:3)
                 


In [83]:
df

nombre edad id
1 Miguel 33   1 
2 Ale    29   2 
3 Israel 28   3

In [84]:
class(df)

[1] "data.frame"

In [85]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ nombre: chr  "Miguel" "Ale" "Israel"
 $ edad  : num  33 29 28
 $ id    : int  1 2 3


In [86]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df[[1]] # Vector con los elementos de nombre
df[1] # dataframe (antes lista) con el vector de nombres


[1] "Miguel" "Ale"    "Israel"

nombre
1 Miguel
2 Ale   
3 Israel

In [87]:
df[["nombre"]]
df[[1]]
df$nombre

[1] "Miguel" "Ale"    "Israel"

[1] "Miguel" "Ale"    "Israel"

[1] "Miguel" "Ale"    "Israel"

In [88]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]

# segunda columna y segunda fila

df[2,2]


nombre edad id
2 Ale    29   2

[1] 29

In [89]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_mascota <- c(F,F,T)

In [90]:
df

nombre edad id tiene_mascota
1 Miguel 33   1  FALSE        
2 Ale    29   2  FALSE        
3 Israel 28   3   TRUE

In [91]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3

# Referenciando el nombre de las columnas
df[,c("nombre","id")]

nombre id
1 Miguel 1 
2 Ale    2 
3 Israel 3

In [92]:
# Referenciando las posiciones de las columnas
df[,c(1,3)]

nombre id
1 Miguel 1 
2 Ale    2 
3 Israel 3

In [93]:
# Se mantiene la lógica de acceso a los sots de una lista.
df$nombre[2]

[1] "Ale"

In [94]:
# Podemos generar nuestras primeras consultas combinando todo lo que hemos visto
df[df$edad >= 29,]

nombre edad id tiene_mascota
1 Miguel 33   1  FALSE        
2 Ale    29   2  FALSE

In [95]:
df$apellido <- c("jorquera", "benavides", "mata")

In [79]:
df

nombre edad id tiene_mascota apellido 
1 Miguel 33   1  FALSE         jorquera 
2 Ale    29   2  FALSE         benavides
3 Israel 28   3   TRUE         mata

In [96]:
df <- df[,c("id", "nombre", "apellido","edad", "tiene_mascota")]

In [100]:
df[,3:5]

apellido  edad tiene_mascota
1 jorquera  33   FALSE        
2 benavides 29   FALSE        
3 mata      28    TRUE