<a href="https://colab.research.google.com/github/majorquev/DBDC_202209_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/Clase2/Clase_2_01_matrices_desarrollo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo. 
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.
 
 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [2]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A

B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [4]:
# clase y atributo dim
class(A)
dim(A)

[1] "matrix" "array"

[1] 2 3

In [5]:
# Genere dos vectores del mismo largo y forme una matriz.
f1 <- c(10,20,30,40)
f2 <- c(-1,-2,-3,-4)




In [9]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind

M <- rbind(f1,f2)
M
M2 <- cbind(f1,f2)
M2

[,1] [,2] [,3] [,4]
f1 10   20   30   40  
f2 -1   -2   -3   -4

f1 f2
[1,] 10 -1
[2,] 20 -2
[3,] 30 -3
[4,] 40 -4

In [12]:
# NOTA: Podemos añadir una fila/columna a una matriz existente
f3 <- c(100,200,300,400)
M3 <- rbind(M,f3)
M3

[,1] [,2] [,3] [,4]
f1  10   20   30   40 
f2  -1   -2   -3   -4 
f3 100  200  300  400

In [18]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)

cbind(1:4, 10:18)



Warning message in cbind(1:4, 10:18):
“number of rows of result is not a multiple of vector length (arg 1)”


[,1] [,2]
 [1,] 1    10  
 [2,] 2    11  
 [3,] 3    12  
 [4,] 4    13  
 [5,] 1    14  
 [6,] 2    15  
 [7,] 3    16  
 [8,] 4    17  
 [9,] 1    18

In [19]:
# función diag para la definición de matrices diagonales
#?diag 

diag(f1)



[,1] [,2] [,3] [,4]
[1,] 10    0    0    0  
[2,]  0   20    0    0  
[3,]  0    0   30    0  
[4,]  0    0    0   40

In [21]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
M3


[,1] [,2] [,3] [,4]
f1  10   20   30   40 
f2  -1   -2   -3   -4 
f3 100  200  300  400

f2 
-1

[1] -1 10

In [22]:
# quiero rescatar el elemento "(2,1)"
M3[2,1]


f2 
-1

In [23]:

# CUIDADO:No es lo mismo que 
M3[c(2,1)] # R entiende también la matriz como un gran vector (por columnas) y lo anterior retorna los elmentos 2 y 1 de dicho vector

[1] -1 10

In [26]:
# Para acceder a una fila completa
M3[2,]


# Para acceder a una columna completa
M3[,3]


[1] -1 -2 -3 -4

f1  f2  f3 
 30  -3 300

In [27]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el -2 por un -99 (el 5 de la pos 2,2)

M3[2,2] <- -99

In [28]:
M3

[,1] [,2] [,3] [,4]
f1  10   20   30   40 
f2  -1  -99   -3   -4 
f3 100  200  300  400

In [30]:
# Acceso mediante nombres
rownames(M3)
colnames(M3)

[1] "f1" "f2" "f3"

NULL

In [31]:
colnames(M3) <- c("c1","c2","c3","c4")

In [32]:
M3

c1  c2  c3  c4 
f1  10  20  30  40
f2  -1 -99  -3  -4
f3 100 200 300 400

In [33]:
# Acceso mediante nomnbres
# Elemento de la segunda fila tercera columna (2,3)

M3["f2","c3"]

[1] -3

In [34]:
# Acceso mediante "indicatrices" lógicas 
#Quiero obtener los elementos (1,1) y (2,3) de M3
# 1: Crear una matriz de 3x4 con TRUE en dichas posiciones y FALSE en las restantes.

ind <- matrix(c(T,F,F,F,F,F,T,F,F,F,F,F), ncol = 4, nrow = 3, byrow = T)
ind


[,1]  [,2]  [,3]  [,4] 
[1,]  TRUE FALSE FALSE FALSE
[2,] FALSE FALSE  TRUE FALSE
[3,] FALSE FALSE FALSE FALSE

In [38]:
ind2 <- matrix(F, nrow = 3, ncol = 4)
ind2

ind2[1,1] <- T
ind2[2,3] <- T

ind2

[,1]  [,2]  [,3]  [,4] 
[1,] FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE FALSE

[,1]  [,2]  [,3]  [,4] 
[1,]  TRUE FALSE FALSE FALSE
[2,] FALSE FALSE  TRUE FALSE
[3,] FALSE FALSE FALSE FALSE

In [39]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M3[ind]

[1] 10 -3

In [42]:
M3 >= 40

c1    c2    c3    c4   
f1 FALSE FALSE FALSE  TRUE
f2 FALSE FALSE FALSE FALSE
f3  TRUE  TRUE  TRUE  TRUE

In [41]:
M3[M3 >= 40]

[1] 100 200 300  40 400

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [ ]:
# transponer una matriz


In [ ]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices



In [ ]:
# Multiplicación de matrices
M2 * M1 # multiplicación componente a componente


In [ ]:
# podemos calcular determinantes
# ?det



In [ ]:
# Podemos invertir matrices
# ?solve
